name: PR to Master

on:
  push:
    branches:
      - dev

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: dev
        destination_branch: master
        pr_title: 'Ready for Production'
        pr_body: 'Automated PR to merge changes from dev to master branch.'
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}